apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Torea\Kompose\kompose.exe convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: raytrakkar-web
  name: raytrakkar-web-nodeport
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    io.kompose.service: raytrakkar-web
status:
  loadBalancer: {}
