apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: D:\Torea\Kompose\kompose.exe convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: raytrakkar-web
  name: raytrakkar-web
spec:
  serviceName: raytrakkar-web
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: raytrakkar-web
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Torea\Kompose\kompose.exe convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: raytrakkar-web
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_IP
          value: "$(POD_NAME).raytrakkar-web"
        - name: CLUSTER_PORT
          value: "5210"
        - name: CLUSTER_SEEDS
          value: akka.tcp://raytrakkar@lighthouse-0.lighthouse:4053
        image: raytrakka.azurecr.io/raytrakkarweb:0.0.6
        imagePullPolicy: ""
        name: raytrakkar-web
        ports:
        - containerPort: 80
        resources: {}
      imagePullSecrets:
        - name: raytrakka-secret
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: 
  replicas: 1
